RestoranUygulaması/Controllers/AuthController.cs
using RestoranUygulaması.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace RestoranUygulaması.Controllers
{
    public class AuthController : Controller
    {
        private Model1 db = new Model1();

        // GET: Login
        [AllowAnonymous]
        public ActionResult Login()
        {
            if (String.IsNullOrEmpty(HttpContext.User.Identity.Name))
            {
                FormsAuthentication.SignOut();
                return View();
            }
            return Redirect("Index");
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(LoginModel model, string returnurl)
        {
            if (ModelState.IsValid)
            {

                var _kullanici = db.Kullanici.Where(k => k.kul_eposta == model.kul_eposta && k.kul_sifre == model.kul_sifre).SingleOrDefault();
                //Aşağıdaki if komutu gönderilen mail ve şifre doğrultusunda kullanıcı kontrolu yapar. Eğer kullanıcı var ise login olur.
                if (_kullanici!=null)
                {
                    Session["kul_ad"] = _kullanici.kul_eposta;
                    FormsAuthentication.SetAuthCookie(model.kul_eposta, true);
                    return RedirectToAction("Index", "Home");
                }

                else
                {
                    ModelState.AddModelError("", "EMail veya şifre hatalı!");
                }
            }
            return View(model);
        }
        public ActionResult logOut()
        {
            Session["kul_ad"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

RestoranUygulaması/Controllers/YemeksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RestoranUygulaması.Models;

namespace RestoranUygulaması.Controllers
{
    public class YemeksController : Controller
    {
        private Model1 db = new Model1();

        // GET: Yemeks
        public ActionResult Index()
        {
            return View(db.Yemek.ToList());
        }

        public ActionResult YemekGör()
        {
            if (Session["kul_ad"] == null)
            {
                return Redirect("Home");

            }
            string kisimizAd = Session["kul_ad"].ToString();
            var kisi = db.Kullanici.Where(i => i.kul_eposta == kisimizAd).SingleOrDefault();
            var yemek = kisi.Yemek.ToList();
            if (yemek == null)
            {
                return RedirectToAction("Create");
            }
            return View(yemek);
        }

        public ActionResult HazirlanisEkle(int id)
        {
            return RedirectToAction("Create", "Hazirlanis", new { id = id });
        }

        public ActionResult FiyatEkle(int id)
        {
            return RedirectToAction("Create", "Fiyats", new { id = id });
        }

        public ActionResult IcindekilerEkle(int id)
        {
            return RedirectToAction("Create", "Icindekilers", new { id = id });
        }

            // GET: Yemeks/Details/5
            public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yemek yemek = db.Yemek.Find(id);
            if (yemek == null)
            {
                return HttpNotFound();
            }
            return View(yemek);
        }

        // GET: Yemeks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Yemeks/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(/*[Bind(Include = "yem_id, yemek_adi")]*/ Yemek yemek)
        {
            if (ModelState.IsValid)
            {
                string kisimizAd = Session["kul_ad"].ToString();
                var kisi = db.Kullanici.Where(i => i.kul_eposta == kisimizAd).SingleOrDefault();
                kisi.Yemek.Add(yemek);
                yemek.Kullanici.Add(kisi);
                db.Yemek.Add(yemek);
                db.SaveChanges();
                return RedirectToAction("YemekGör");
            }

            return View(yemek);
        }

        // GET: Yemeks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yemek yemek = db.Yemek.Find(id);
            if (yemek == null)
            {
                return HttpNotFound();
            }
            return View(yemek);
        }

        // POST: Yemeks/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "yem_id,yemek_adi")] Yemek yemek)
        {
            if (ModelState.IsValid)
            {
                db.Entry(yemek).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(yemek);
        }

        // GET: Yemeks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yemek yemek = db.Yemek.Find(id);
            if (yemek == null)
            {
                return HttpNotFound();
            }
            return View(yemek);
        }

        // POST: Yemeks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Yemek yemek = db.Yemek.Find(id);
            db.Yemek.Remove(yemek);
            db.SaveChanges();
            return RedirectToAction("YemekGör");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RestoranUygulaması/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
    <html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - ASP.NET Uygulamam</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Uygulama adı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Giriş Sayfası", "Index", "Home")</li>
                        <li>@Html.ActionLink("Hakkında", "About", "Home")</li>
                        <li>@Html.ActionLink("Kişi", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Session["kul_ad"] == null)
                {
                    @Html.ActionLink("Restaurant", "Login", "Auth", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Anasayfa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Yemek", "Index", "Yemeks", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Hakkımızda", "Index", "Hakkimizdas", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("BasındaBiz", "Index", "BasindaBizs", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Rezervasyon", "Index", "Rezervasyons", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("Yemek Kayıt", "Index", "Yemeks/Create", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Basın Kayıt", "Index", "BasindaBizs/Create", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Hakkımızda Kayıt", "Login", "Hakkimizdas/Create", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("BasınGör", "BasinGör", "BasindaBizs", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("YemekGör", "YemekGör", "Yemeks", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("HakkımızdaGör", "HakkimizGör", "Hakkimizdas", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("RezervasyonGör", "RezervasyonGör", "Rezervasyons", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Çıkış Yap", "Logout", "Auth", new { area = "" }, new { @class = "navbar-brand" })






                }
            </div>
            @*<div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Giriş Sayfası", "Index", "Home")</li>
                        <li>@Html.ActionLink("Hakkında", "About", "Home")</li>
                        <li>@Html.ActionLink("Kişi", "Contact", "Home")</li>
                    </ul>
                </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>